INSERT INTO INSTRUMENT_PRICE_MODIFIER (name, multiplier) VALUES ('INSTRUMENT1', 1.05);
INSERT INTO INSTRUMENT_PRICE_MODIFIER (name, multiplier) VALUES ('INSTRUMENT2', 1.10);
INSERT INTO INSTRUMENT_PRICE_MODIFIER (name, multiplier) VALUES ('INSTRUMENT3', 1.15);
INSERT INTO INSTRUMENT_PRICE_MODIFIER (name, multiplier) VALUES ('INSTRUMENT5', 2);