INSERT INTO INSTRUMENT_PRICE_MODIFIER (id, name, multiplier) VALUES (1, 'INSTRUMENT1', 1.05);
INSERT INTO INSTRUMENT_PRICE_MODIFIER (id, name, multiplier) VALUES (2, 'INSTRUMENT2', 1.10);
INSERT INTO INSTRUMENT_PRICE_MODIFIER (id, name, multiplier) VALUES (3, 'INSTRUMENT3', 1.15);
INSERT INTO INSTRUMENT_PRICE_MODIFIER (id, name, multiplier) VALUES (4, 'INSTRUMENT5', 2);